name: PerchElevator
version: '${version}'
api-version: 1.13
author: KayaLambrex
main: me.perch.elevator.ElevatorPlugin
softdepend:
  - Essentials
permissions:
  perchelevator.reload:
    description: Permission to reload PerchElevator config.
    default: op