name: PerchElevator
version: '${version}'
api-version: 1.13
author: KayaLambrex
main: me.perch.elevator.Main
softdepend:
  - Essentials
commands:
  perchelevator:
    usage: /perchelevator reload
    description: Reloads the PerchElevator config
    permission: perchelevator.reload
permissions:
  perchelevator.reload:
    description: Permission to reload PerchElevator config.
    default: op