name: PerchElevator
version: 1.0.0
api-version: 1.13
author: KayaLambrex
main: com.live.bemmamin.elevator.Main
softdepend:
  - Essentials
  - CMI
  - Factions
  - SunLight
  - CombatLogX
commands:
  elevator:
    usage: /elevator
    description: Normal elevator commands.
    aliases: [ simpleelevators, elevators, se ]
  elevatoradmin:
    usage: /elevatoradmin
    description: Admin elevator commands
    aliases: [ simpleelevatorsadmin, elevatorsadmin, elevatoradmin, sea ]
permissions:
  elevator.commands:
    description: Permission to use commands.
  elevator.commands.help:
    description: Permission to use the help command.
  elevator.commands.create:
    description: Permission to use the create command.
  elevator.commands.list:
    description: Permission to use the list command.
  elevator.admin:
    description: Permission to use admin commands.
  elevator.update:
    description: Permission to receive update notifications.
  elevator.bypass.cooldown:
    description: Permission to bypass cooldown.
  elevator.bypass.distance:
    description: Permission to bypass distance.
  elevator.use:
    description: Permission to use elevators.
    default: true